[
{
    "result": {
        "title": "Transformers: The Last Knight (2017)",
        "link": "http://167.99.71.200/transformers-the-last-knight-2017/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2017/08/f8Ng1Sgb3VLiSwAvrfKeQPzvlfr.jpg",
        "genre": "Action, Adventure, Science Fiction, Thriller",
        "views": "24.042 views",
        "duration": "149 Menit",
        "tahun": "2017",
        "rating": "6,2/10",
        "desc": "Autobots and Decepticons are at war, with humans on the sidelines. Optimus Prime is gone. The key to saving our future lies buried in the secrets of the past, in the hidden history of Transformers on Earth.",
        "actors": [
            "Adam Lazarus",
            "Aisha Kabia",
            "Aiyaz Ahmed",
            "Alan Pietruszewski",
            "Andy Bean",
            "Anthony Hopkins",
            "Barbara Eve Harris",
            "Ben Webb",
            "Benjamin Flores Jr.",
            "Bern Collaco",
            "Bernardo Santos",
            "Brian William Price",
            "Charlie Bouguenon",
            "Christian Wolf-La’Moy",
            "Christina Tam",
            "Christoper Vasquez",
            "Claude Knowlton",
            "Dan Warner",
            "Daniel Adegboyega",
            "Daniel Iturriaga",
            "David Macey",
            "David Olawale Ayinde",
            "Deborah Rock",
            "Dino Fazzani",
            "Drew B. Waters",
            "Edward Mannering",
            "Elizabeth Croft",
            "Eloise Henwood",
            "Emily Tierney",
            "Erik Aadahl",
            "Frank Welker",
            "Gemma Chan",
            "Glenn Morshower",
            "Graham Curry",
            "Granville Ames",
            "Helen Iesha Goldthorpe",
            "Honey Holmes",
            "Isabela Moner",
            "Jacob Zachar",
            "Jag Patel",
            "Jandre le Roux",
            "Jason Matthewson",
            "Jerrod Carmichael",
            "Jess Harnell",
            "Jill Buchanan",
            "Jim Carter",
            "Jim Wisniewski",
            "John Burke",
            "John DiMaggio",
            "John Goodman",
            "John Hollingworth",
            "John Turturro",
            "Joost Janssen",
            "Josh Duhamel",
            "Juliocesar Chavez",
            "Karl Farrer",
            "Ken Watanabe",
            "Kevin Kent",
            "Krista Schaeffer",
            "Laura Haddock",
            "Leighton Sharpe",
            "Liam Garrigan",
            "Maggie Steed",
            "Marcus Fraser",
            "Mark Dexter",
            "Mark Ryan",
            "Mark Wahlberg",
            "Martin McCreadie",
            "Matthew Castle",
            "Mia Maria",
            "Michael Chapman",
            "Minti Gorne",
            "Mitch Pileggi",
            "Nicholas Khan",
            "Nicola Peltz",
            "Omar Sy",
            "Pauline McLynn",
            "Perry Yee",
            "Peter Cullen",
            "Peter Meyer",
            "Phill Langhorne",
            "Phoebe Nicholls",
            "Poppy Carter",
            "Rebecca Front",
            "Remi Adeleke",
            "Reno Wilson",
            "Rob Jarvis",
            "Rob Witcomb",
            "Sam Yim",
            "Samuel Parker",
            "Santiago Cabrera",
            "Sara Stewart",
            "Seeta Indrani",
            "Simon Harrison",
            "Sofia Abbasi",
            "Sophia Myles",
            "Stanley Tucci",
            "Stephen Hogan",
            "Steve Buscemi",
            "Steven Barr",
            "Tim Downie",
            "Tom Dab",
            "Tom Kenny",
            "Tom Wright",
            "Tony Hale",
            "Ty Hurley",
            "Vincent Jerome",
            "Walles Hamonde",
            "Wendy Albiston",
            "Wolfgang Young"
        ],
        "location": "USA",
        "date_release": "21 Jun 2017",
        "language": "English",
        "link_dl": "https://oload.tv/f/8qBhtu16nWk/Transformers.The.Last.Knight.2017.720p.HC.HDRip.MkvCage.mkv"
    }
},
{
    "result": {
        "title": "Monster Hunter (2021)",
        "link": "http://167.99.71.200/monster-hunter-2020/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2021/01/zO9R7Z6DRDgRO9QVz4lAJg3L15o.jpg",
        "genre": "Action, Adventure, Fantasy",
        "views": "24.350 views",
        "duration": "104 Menit",
        "tahun": "2020",
        "rating": "5,6/10",
        "desc": "A portal transports Lt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.",
        "actors": [
            "Aaron Beelner",
            "Adrián Muñoz",
            "Diego Boneta",
            "Hirona Yamazaki",
            "Jannik Schümann",
            "Jin Au-Yeung",
            "Josh Helman",
            "Meagan Good",
            "Milla Jovovich",
            "Nanda Costa",
            "Nic Rasenti",
            "Ron Perlman",
            "Schelaine Bennett",
            "T.I.",
            "Tony Jaa"
        ],
        "location": "Canada",
        "date_release": "3 Dec 2020",
        "language": "English",
        "link_dl": "https://acefile.co/f/34661286"
    }
},
{
    "result": {
        "title": "The Predator (2018)",
        "link": "http://167.99.71.200/the-predator/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2018/09/wMq9kQXTeQCHUZOG4fAe5cAxyUA.jpg",
        "genre": "Action, Adventure, Comedy, Horror, Science Fiction",
        "views": "59.704 views",
        "duration": "107 Menit",
        "tahun": "2018",
        "rating": "5,6/10",
        "desc": "From the outer reaches of space to the small-town streets of suburbia, the hunt comes home. Now, the universe’s most lethal hunters are stronger, smarter and deadlier than ever before, having genetically upgraded themselves with DNA from other species. When a young boy accidentally triggers their return to Earth, only a ragtag crew of ex-soldiers and a disgruntled science teacher can prevent the end of the human race.",
        "actors": [
            "Alfie Allen",
            "Andrew Jenkins",
            "Anousha Alamian",
            "Augusto Aguilera",
            "Boyd Holbrook",
            "Brian A. Prince",
            "Byron Briscoe",
            "Colin Corrigan",
            "Crystal Mudry",
            "Dean Redman",
            "Devielle Johnson",
            "Eduard Witzke",
            "Edward James Olmos",
            "Gabriel LaBelle",
            "Garry Chalk",
            "Harrison MacDonald",
            "Inka Malovic",
            "J.C. Williams",
            "Jacob Tremblay",
            "Jake Busey",
            "Javier Lacroix",
            "Jay Hector",
            "Kathryn Marie Robinson",
            "Keegan-Michael Key",
            "Kory Grim",
            "Kyle Strauts",
            "Lochlyn Munro",
            "Malcolm Masters",
            "Marcio Moreno",
            "Mathew Yanagiya",
            "Niall Matter",
            "Nikolas Dukic",
            "Olivia Munn",
            "Patrick Sabongui",
            "Paul Lazenby",
            "Rhys Williams",
            "RJ Fetherstonhaugh",
            "Sarah Ziolkowski",
            "Sean Kohnke",
            "Sterling K. Brown",
            "Steve Wilder",
            "Thomas Jane",
            "Trevante Rhodes",
            "Vin Asim",
            "Yvonne Strahovski"
        ],
        "location": "USA",
        "date_release": "13 Sep 2018",
        "language": "English",
        "link_dl": "https://www.rapidvideo.com/d/G1AU28U9NY"
    }
},
{
    "result": {
        "title": "The Midnight Sky (2020)",
        "link": "http://167.99.71.200/the-midnight-sky-2020/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2021/04/tbI9bhZlYmfWGkqY1Wje9Sg3He9-1.jpg",
        "genre": "Drama, Science Fiction",
        "views": "2.016 views",
        "duration": "118 Menit",
        "tahun": "2020",
        "rating": "5,9/10",
        "desc": "A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.",
        "actors": [
            "Atli Óskar Fjalarsson",
            "Bharat Mistri",
            "Caoilinn Springall",
            "David Oyelowo",
            "Demián Bichir",
            "Edan Hayhurst",
            "Ethan Peck",
            "Eysis Clacken",
            "Felicity Jones",
            "George Clooney",
            "Grant Crookes",
            "Gsus Lopez",
            "Hanna María Karlsdóttir",
            "Jamie Schneider",
            "Jill Buchanan",
            "Kishore Bhatt",
            "Kyle Chandler",
            "Lilja Nótt Þórarinsdóttir",
            "Miriam Shor",
            "Natasha Jenssen",
            "Paul Riddell",
            "Sam Bond",
            "Sophie Rundle",
            "Tia Bannon",
            "Tiffany Boone",
            "Tim Russ"
        ],
        "location": "USA",
        "date_release": "10 Dec 2020",
        "language": "English",
        "link_dl": "https://acefile.co/f/33999254"
    }
},
{
    "result": {
        "title": "The Odd Family: Zombie on Sale (2019)",
        "link": "http://167.99.71.200/the-odd-family-zombie-on-sale-2019-2/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2019/12/cmflq3HXg8rNbviAnP6kwzKcJ9T.jpg",
        "genre": "Comedy, Drama, Fantasy, Horror",
        "views": "6.357 views",
        "duration": "112 Menit",
        "tahun": "2019",
        "rating": "6,0/10",
        "desc": "An affluent neighborhood family is visited by a zombie.",
        "actors": [
            "Jeon Bae-soo",
            "Jung Ga-ram",
            "Jung Jae-young",
            "Kim Ki-chun",
            "Kim Nam-gil",
            "Lee Soo-kyung",
            "Park Hye-sook",
            "Park In-hwan",
            "Shin Jung-geun",
            "Uhm Ji-won"
        ],
        "location": "Korea",
        "date_release": "13 Feb 2019",
        "language": "한국어/조선말",
        "link_d": ""
    }
},
{
    "result": {
        "title": "Avengers: Endgame (2019)",
        "link": "http://167.99.71.200/avengers-endgame-2019/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2019/04/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
        "genre": "Action, Adventure, Science Fiction",
        "views": "268.571 views",
        "duration": "181 Menit",
        "tahun": "2019",
        "rating": "8,7/10",
        "desc": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos’ actions and restore order to the universe once and for all, no matter what consequences may be in store.",
        "actors": [
            "Aaron Lazar",
            "Ameenah Kaplan",
            "Angela Bassett",
            "Anthony Mackie",
            "Ava Russo",
            "Bazlo LeClair",
            "Ben Sakamoto",
            "Benedict Cumberbatch",
            "Benedict Wong",
            "Bradley Cooper",
            "Brent McGee",
            "Brian Schaeffer",
            "Brie Larson",
            "Cade Woodward",
            "Callan Mulvey",
            "Chadwick Boseman",
            "Chris Evans",
            "Chris Hemsworth",
            "Chris Pratt",
            "Cobie Smulders",
            "Danai Gurira",
            "Dave Bautista",
            "Don Cheadle",
            "Elizabeth Olsen",
            "Emma Fuhrmann",
            "Evangeline Lilly",
            "Frank Grillo",
            "Gwyneth Paltrow",
            "Hayley Atwell",
            "Hiroyuki Sanada",
            "Hye Jin Jang",
            "Jack Champion",
            "Jackson A. Dunn",
            "Jacob Batalon",
            "James D’Arcy",
            "Jeremy Renner",
            "Jim Starlin",
            "Jimmy Ray Pickens",
            "Joe Russo",
            "John Michael Morris",
            "John Posey",
            "John Slattery",
            "Jon Favreau",
            "Josh Brolin",
            "Karen Gillan",
            "Ken Jeong",
            "Kerry Condon",
            "Lee Moore",
            "Letitia Wright",
            "Lexi Rabe",
            "Lia Russo",
            "Linda Cardellini",
            "Loen LeClair",
            "Marisa Tomei",
            "Mark Ruffalo",
            "Matthew Berry",
            "Maximiliano Hernández",
            "Michael A. Cook",
            "Michael Douglas",
            "Michael James Shaw",
            "Michelle Pfeiffer",
            "Mike Lutz",
            "Monique Ganderton",
            "Natalie Portman",
            "Olaniyan Thurmon",
            "Patrick Gorman",
            "Paul Rudd",
            "Pom Klementieff",
            "Rene Russo",
            "Robert Downey Jr.",
            "Robert Pralgo",
            "Robert Redford",
            "Ross Marquand",
            "Russell Bobbitt",
            "Sam Hargrave",
            "Samuel L. Jackson",
            "Scarlett Johansson",
            "Sean Gunn",
            "Sebastian Stan",
            "Stan Lee",
            "Taika Waititi",
            "Terry Notary",
            "Tessa Thompson",
            "Tilda Swinton",
            "Tom Hiddleston",
            "Tom Holland",
            "Tom Vaughan-Lawlor",
            "Ty Simpkins",
            "Vin Diesel",
            "William Hurt",
            "Winston Duke",
            "Yvette Nicole Brown",
            "Zoe Saldana"
        ],
        "location": "USA",
        "date_release": "24 Apr 2019",
        "language": "English",
        "link_dl": "https://acefile.co/f/12715461"
    }
},
{
    "result": {
        "title": "Killer Weekend (2020)",
        "link": "http://167.99.71.200/killer-weekend-2020/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2020/10/iyzMeofrUVYyiPoItBcKjRgxlIh.jpg",
        "genre": "Thriller",
        "views": "1.137 views",
        "duration": "90 Menit",
        "tahun": "2020",
        "rating": "",
        "desc": "A sexy young coed enjoys a lavish lifestyle thanks to a sugar daddy dating app, accessing their money by having them killed. She soon meets her match, however, in her new rich, handsome boyfriend – who happens to also be a serial killer.",
        "actors": [
            "Alex Urbom",
            "Andy Davoli",
            "Caitlin Keats",
            "Catherine McCafferty",
            "Chad Christopher",
            "Jennifer Blanc",
            "Michael Biehn",
            "Nikita Black",
            "Richard Gunn",
            "Sarah Blades",
            "Vanessa Zima"
        ],
        "location": "Australia",
        "date_release": "26 Oct 2020",
        "language": "English",
        "link_dl": "https://acefile.co/f/30639432/gm21-live-killer-weekend-mp4"
    }
},
{
    "result": {
        "title": "Strain 100 (2020)",
        "link": "http://167.99.71.200/strain-100-2020/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2020/12/6bf4ht5c5ujYbUgrIo526FL2dOB-1.jpg",
        "genre": "Adventure, Horror",
        "views": "1.373 views",
        "duration": "84 Menit",
        "tahun": "2020",
        "rating": "5,0/10",
        "desc": "After surviving a terrifying car crash, a young woman discovers that aggressive, flesh-eating zombies have overtaken the entire area. She must figure out what is happening and why in hopes of escaping her horrifying circumstances.",
        "actors": [
            "Alexis Boozer Sterling",
            "Erika Hoveland",
            "Jemma Dallender",
            "Jennifer Jelsema",
            "Julie Kline",
            "Keyna Reynolds",
            "Matt Carriker",
            "Sara Holden"
        ],
        "location": "USA",
        "date_release": "22 Oct 2020",
        "language": "English",
        "link_dl": "https://acefile.co/f/34031531"
    }
},
{
    "result": {
        "title": "Thor: Love and Thunder (2021)",
        "link": "http://167.99.71.200/thor-love-and-thunder-2021/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2020/04/lrPMm9aFndk556vbRfnv0F8mrlS.jpg",
        "genre": "Action, Adventure, Fantasy",
        "views": "53.849 views",
        "duration": "",
        "tahun": "2021",
        "rating": "",
        "desc": "The fourth installment of the Marvel Studios’ Thor movie series.",
        "actors": [
            "Bradley Cooper",
            "Chris Hemsworth",
            "Chris Pratt",
            "Christian Bale",
            "Dave Bautista",
            "Karen Gillan",
            "Natalie Portman",
            "Pom Klementieff",
            "Sean Gunn",
            "Taika Waititi",
            "Tessa Thompson",
            "Vin Diesel"
        ],
        "location": "USA",
        "date_release": "28 Oct 2021",
        "language": "English",
        "link_d": ""
    }
},
{
    "result": {
        "title": "Useless Humans (2020)",
        "link": "http://167.99.71.200/useless-humans-2020/",
        "thumbnail": "http://167.99.71.200/wp-content/uploads/2020/11/a8MMTMoZRakarCowUeVuWKo8jYy.jpg",
        "genre": "Adventure, Comedy, Horror",
        "views": "368 views",
        "duration": "77 Menit",
        "tahun": "2020",
        "rating": "4,0/10",
        "desc": "A thirtieth birthday — and the survival of mankind — are left hanging in the balance after a mysterious creature crashes the party, forcing four childhood friends to save the night.",
        "actors": [
            "Davida Williams",
            "Edy Ganem",
            "Josh Zuckerman",
            "Luke Youngblood",
            "Maya Kazan",
            "Rushi Kota"
        ],
        "location": "China",
        "date_release": "14 Jul 2020",
        "language": "English",
        "link_dl": "https://acefile.co/f/31964211"
    }
}
]